#!/bin/sh
[ $# -ne 1 ] && {
	echo "Usage: git vimstage <file>"
	exit 1
}
DEDITOR=$(git config --get vimstage.editor || echo vimdiff)
test -z "$EDITOR" && EDITOR="vi"

set -e -x

tmp=$(mktemp --suffix=.vimstage)
top=$(git rev-parse --show-toplevel)
file=$(realpath "$1")
file=${file#$top/}
cd "$top"
(
	if git ls-files --stage --error-unmatch -- "$file" >/dev/null 2>&1; then
		git show :"$file" > "$tmp"
		"$DEDITOR" "$tmp" "$file"
		mode=$(git ls-files --stage -- "$file" | cut -d' ' -f1)
	else
		cp "$file" "$tmp"
		"$EDITOR" "$tmp"
		case "$(uname -s)" in
			Linux) mode=100$(stat --format %a "$file") ;;
			FreeBSD) mode=$(stat -f %p "$file") ;;
			*)
				echo "WARNING: unsupported OS, assuming rw-r--r--"
				mode=100644
				;;
		esac
	fi
	hash=$(git hash-object -t blob -w --path="$file" -- "$tmp")
	git update-index --add --cacheinfo "$mode,$hash,$file"
)
rm -f "$tmp"
