#!/bin/sh
set -e -x
current=$(mktemp --suffix=.vimstage)
(
	future=$(mktemp --suffix=.vimstage)
	(
		git show :./"$1" > "$current"
		cp "$current" "$future"
		vimdiff "$future" "$1"
		diff -u --label="./$1"{,} "$current" "$future" | git apply --cached
	)
	rm -f "$future"
)
rm -f "$current"
