#!/bin/sh
[ $# -ne 1 ] && {
	echo "Usage: git vimstage <file>"
	exit 1
}
DEDITOR=$(git config --get vimstage.editor || echo vimdiff)
test -z "$EDITOR" && EDITOR=vi

set -e -x

current=$(mktemp --suffix=.vimstage)
file="$(git rev-parse --show-prefix)${1#./}"
(
	if git ls-files --stage --error-unmatch "$file" >/dev/null 2>&1; then
		future=$(mktemp --suffix=.vimstage)
		(
			git show :"$file" > "$current"
			cp "$current" "$future"
			"$DEDITOR" "$future" "$1"
			diff -u --label="$file"{,} "$current" "$future" | git apply --cached
		)
		rm -f "$future"
	else
		cp "$1" "$current"
		"$EDITOR" "$current"
		diff -u /dev/null --label /dev/null --label "$file" "$current" | git apply --cached
	fi
)
rm -f "$current"
